// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CreateTodo implements createTodo operation.
//
// Create a new TODO item.
//
// POST /todos
func (UnimplementedHandler) CreateTodo(ctx context.Context, req *CreateTodoRequest) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteTodo implements deleteTodo operation.
//
// Delete a specific TODO item.
//
// DELETE /todos/{id}
func (UnimplementedHandler) DeleteTodo(ctx context.Context, params DeleteTodoParams) error {
	return ht.ErrNotImplemented
}

// GetTodo implements getTodo operation.
//
// Get a specific TODO item.
//
// GET /todos/{id}
func (UnimplementedHandler) GetTodo(ctx context.Context, params GetTodoParams) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTodos implements listTodos operation.
//
// Get all TODO items.
//
// GET /todos
func (UnimplementedHandler) ListTodos(ctx context.Context) (r []Todo, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateTodo implements updateTodo operation.
//
// Update a specific TODO item.
//
// PUT /todos/{id}
func (UnimplementedHandler) UpdateTodo(ctx context.Context, req *UpdateTodoRequest, params UpdateTodoParams) (r *Todo, _ error) {
	return r, ht.ErrNotImplemented
}
